version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Tag}}
    main: ./cmd/micro-api

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

dockers:
  - image_templates:
      - ghcr.io/fernandezvara/microapi:{{ .Tag }}-amd64
    dockerfile: Dockerfile
    use: buildx
    goarch: amd64
    goos: linux
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Tag}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --platform=linux/amd64
      - --build-arg=ARCH=amd64
  - image_templates:
      - ghcr.io/fernandezvara/microapi:{{ .Tag }}-arm64
    dockerfile: Dockerfile
    goarch: arm64
    goos: linux
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Tag}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --platform=linux/arm64
      - --build-arg=ARCH=arm64

docker_manifests:
  - name_template: ghcr.io/fernandezvara/microapi:{{ .Tag }}
    image_templates:
      - ghcr.io/fernandezvara/microapi:{{ .Tag }}-amd64
      - ghcr.io/fernandezvara/microapi:{{ .Tag }}-arm64
  - name_template: ghcr.io/fernandezvara/microapi:latest
    image_templates:
      - ghcr.io/fernandezvara/microapi:{{ .Tag }}-amd64
      - ghcr.io/fernandezvara/microapi:{{ .Tag }}-arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
